### PR TITLE
convert Makefile.PL to Build.PL

### PR DESCRIPTION
**Pull request by dnozay**
used `Module::Build::Convert` to convert `ExtUtils::MakeMaker`-style `Makefile.PL` to a `Module::Build`-style `Build.PL`.

### CODE REVIEW

**Comment by muir** [comment]
The Build.PM file you've made doesn't rebuild the README file (unlike the Makefile.PM)

**Comment by muir** [comment]
See http://blogs.perl.org/users/michal_wojciechowski/2011/11/github-friendly-readme-files-with-extutils-makemaker-and-module-build.html

I'm perfectly happy with the Makefile.PL and "make test" but I'm willing to switch to Build.PL

**Comment by dnozay** [comment]
`./Build dist` or `./Build distmeta` will rebuild the `README` file.
This is what the `create_readme => 1` does.

**Comment by muir** [comment]
I'm not sure why this isn't already marked closed.

**Pull request closed without merging**
